import LegalLayout from "../components/LegalLayout";

export const metadata = {
  title: "Terms and Conditions - Business Audit",
};

export default function TermsPage() {
  return (
    <LegalLayout title="Terms and Conditions" lastUpdated="14 June 2026">
      <h2>1. Who we are</h2>
      <p>
        Business Audit is operated by T3 Labs. For questions, contact us at{" "}
        <a href="mailto:hello@t3labs.co.uk">hello@t3labs.co.uk</a>.
      </p>
      <p>
        Company number: [Not yet registered]<br />
        VAT number: [Not yet registered]<br />
        Registered address: [Not yet registered]
      </p>

      <h2>2. What Business Audit is</h2>
      <p>
        Business Audit is an AI-assisted diagnostic tool. It uses the answers you provide to generate a written report intended to help you think about your business. It is not a regulated advice service.
      </p>
      <p>
        Results are generated automatically using artificial intelligence. They are for informational purposes only. They do not constitute legal, financial, accounting, tax, employment, investment, or any other regulated professional advice.
      </p>
      <p>
        We cannot guarantee that any recommendation will produce a specific outcome. Results will vary depending on your circumstances.
      </p>

      <h2>3. Who can use this service</h2>
      <p>
        You must be at least 18 years old to use Business Audit. By using this service, you confirm that you are 18 or over and that you are acting in a business capacity, not as a consumer purchasing for personal use.
      </p>

      <h2>4. The free audit</h2>
      <p>
        Completing the questionnaire is free. Your free result is generated from your answers using AI. No payment is required to receive the free insight.
      </p>

      <h2>5. The paid audit report</h2>
      <p>
        You can choose to purchase a full audit report for £9. This is a one-off payment processed via Stripe.
      </p>
      <p>
        The paid report is a digital product generated instantly upon payment. By purchasing, you agree to receive immediate digital access and acknowledge that, once the report has been generated, you may lose your right to cancel or request a refund under the Consumer Contracts Regulations 2013, unless there is a technical fault or the report was not delivered.
      </p>
      <p>
        If you experience a technical issue and do not receive your report, contact us at{" "}
        <a href="mailto:hello@t3labs.co.uk">hello@t3labs.co.uk</a> and we will resolve it.
      </p>

      <h2>6. The free Audit Review Call</h2>
      <p>
        Paid audit customers receive access to a free 15-minute Audit Review Call via Calendly. This call is optional. It is a coaching-style conversation to help you understand your audit results - it is not a regulated advisory service.
      </p>
      <p>
        We reserve the right to limit availability of review calls or to withdraw this offer with reasonable notice.
      </p>

      <h2>7. Your answers and data</h2>
      <p>
        You must not include personal data of third parties (such as customer names, employee details, or private financial information) in your questionnaire answers. Your answers are used solely to generate your audit report. See our{" "}
        <a href="/business-audit/privacy">Privacy Policy</a> for full details on how we handle your data.
      </p>

      <h2>8. Intellectual property</h2>
      <p>
        All content on this site, including the questionnaire structure, report format, and generated insights, is owned by or licensed to T3 Labs. You may use your own audit report for your own business purposes but may not reproduce or resell it commercially.
      </p>

      <h2>9. Limitation of liability</h2>
      <p>
        To the fullest extent permitted by law, T3 Labs is not liable for any business loss, loss of profit, loss of revenue, loss of data, or indirect or consequential loss arising from your use of the Business Audit tool or reliance on any report generated by it.
      </p>
      <p>
        Our total liability to you for any claim arising from use of Business Audit shall not exceed the amount you paid for the paid audit report (if any).
      </p>

      <h2>10. Changes to these terms</h2>
      <p>
        We may update these terms from time to time. The current version will always be available at this URL. Continued use of the service after changes are published constitutes acceptance of the updated terms.
      </p>

      <h2>11. Governing law</h2>
      <p>
        These terms are governed by the laws of England and Wales. Any disputes will be subject to the exclusive jurisdiction of the courts of England and Wales.
      </p>

      <h2>12. Contact</h2>
      <p>
        For any questions about these terms, email us at{" "}
        <a href="mailto:hello@t3labs.co.uk">hello@t3labs.co.uk</a>.
      </p>
    </LegalLayout>
  );
}
