export const websitePackageTerms = {
  legalEntityName: "T3 Play Limited",
  tradingName: "T3 Labs",
  companyNumber: "",
  nzbn: "",
  registeredOffice: "",
  registeredJurisdiction: "New Zealand",
  businessEmail: "insights@t3labs.co.uk",
  businessPhone: "",
  privacyOfficerEmail: "insights@t3labs.co.uk",
  packagePrice: "\u00a3399",
  taxTreatment: "\u00a3399 total - no separate UK VAT or New Zealand GST amount added",
  vatStatus: "\u00a3399 total - no separate UK VAT or New Zealand GST amount added",
  invoiceCurrency: "GBP",
  proposalValidityDays: 30,
  depositPercentage: 50,
  depositAmount: "\u00a3199.50",
  finalPaymentAmount: "\u00a3199.50",
  invoicePaymentDays: 7,
  revisionRounds: 1,
  handoverMinutes: 20,
  includedHostingMonths: 3,
  monthlyHostingPrice: "\u00a310",
  hostingReminderDays: 14,
  supportResponseWorkingDays: 2,
  estimatedDeliveryWorkingDaysMin: 7,
  estimatedDeliveryWorkingDaysMax: 10,
  governingLaw: "New Zealand",
  courts: "the courts of New Zealand",
  sourceCodeTransferPolicy: "[CONFIRMED POLICY]",
  ownershipPolicy: "[CONFIRMED POLICY]",
  formHostingModel: "[FORM HOSTING MODEL]",
  formRetentionPeriod: "[RETENTION PERIOD]",
  callMinutes: 20,
  termsVersion: "2026-07-15",
  privacyVersion: "2026-07-15",
  cookieVersion: "2026-07-15",
  cookiePolicyVersion: "2026-07-15",
  consentVersion: "2026-07-15",
  lastUpdated: "2026-07-15",
} as const;

export function pluralise(count: number, singular: string, plural = `${singular}s`) {
  return count === 1 ? singular : plural;
}

export const proposalLegalLinks = [
  { label: "Website Package Terms", href: "/website-package-terms" },
  { label: "Privacy Notice", href: "/privacy" },
  { label: "Cookie Policy", href: "/cookies" },
  { label: "Cookie Settings", href: "#cookie-settings" },
  { label: "Request Removal", href: "#request-removal" },
  { label: "Contact T3 Labs", href: "#contact-t3-labs" },
] as const;
