import type { PremiumContractorConfig } from "@/types/premium-contractor";

const asset = (name: string) => `/assets/3a-roofing-wp-000207/${name}`;

export const threeARoofingPremiumSite = {
  basePath: "/3a-roofing",
  company: {
    name: "3A Roofing Ltd",
    shortName: "3A Roofing",
    legalName: "3A Roofing Ltd",
    tagline: "Roofing Our Heritage",
    description: "Heritage roofing, traditional craft and complete reroofing from Copdock, near Ipswich.",
    logo: { src: asset("3a-roofing-wordmark.png"), alt: "3A Roofing Ltd — Roofing Our Heritage" },
    logoLight: { src: asset("3a-roofing-wordmark.png"), alt: "3A Roofing Ltd — Roofing Our Heritage" },
  },
  branding: {
    primaryColour: "#171A18",
    accentColour: "#3F6393",
    accentLightColour: "#D7DEE8",
    heroAccentColour: "#EBEBEB",
    backgroundColour: "#EBEBEB",
    textColour: "#222222",
    mutedColour: "#666A70",
  },
  contact: {
    phone: "01473 730 666",
    phoneHref: "tel:+441473730666",
    email: "enquiries@3aroofing.co.uk",
    address: "The Laurels, Copdock, Suffolk, IP8 3JF",
    openingHours: "Enquiries by telephone or email",
  },
  navigation: { showServices: true, showQuote: true, showProjects: true, showProcess: true },
  hero: {
    eyebrow: "Heritage roofing specialists · Suffolk",
    heading: "Traditional roofing craft for buildings that matter.",
    supportingText: "Historic conservation, slating, tiling and leadwork for heritage, listed and ecclesiastical buildings — alongside complete reroofing for Suffolk homes.",
    image: { src: asset("hero-heritage-estate-roof.webp"), alt: "Aerial view of a historic estate with renewed slate roofs and ornate brick chimneys" },
    primaryCta: "Request a quotation",
    secondaryCta: "Explore our work",
    credibilityNote: "Based in Copdock, near Ipswich, working across Suffolk",
  },
  introduction: {
    eyebrow: "Roofing our heritage",
    heading: "Conservation knowledge and traditional skill, applied with care.",
    paragraphs: [
      "Established in 2003, 3A Roofing is a family-owned company based in Copdock, near Ipswich. The team combines practical experience in heritage tiling, slating and leadwork with academic qualification to master’s degree level in Historic Conservation.",
      "From timber-framed vernacular buildings to Georgian, Victorian and Edwardian architecture, the approach begins with understanding the building, selecting sympathetic materials and protecting its character for the future.",
    ],
    image: { src: asset("leadwork-turret-detail.webp"), alt: "Detailed leadwork around the base of a historic roof turret" },
  },
  trustItems: [
    { title: "Heritage Craft Roofer", supportingText: "Included on the National Heritage Roofing Contractors Register." },
    { title: "Historic Conservation", supportingText: "Knowledge supported by master’s degree-level qualification." },
    { title: "Which? Trusted Trader", supportingText: "An established roofing company serving private and professional clients." },
    { title: "Established in 2003", supportingText: "Family-owned and based near Ipswich in Suffolk." },
  ],
  services: [
    {
      id: "heritage-listed-roofing",
      name: "Heritage & listed roofing",
      shortDescription: "Conservation-led roofing for listed, heritage and ecclesiastical buildings.",
      fullDescription: "Historic roofs call for an understanding of the building as well as the covering. 3A Roofing undertakes work to listed, heritage and ecclesiastical buildings with careful attention to traditional character and appropriate materials.",
      image: { src: asset("historic-flint-chapel-roof.webp"), alt: "Historic flint building with arched windows and a traditional tiled roof" },
      projectTypes: ["Listed buildings", "Ecclesiastical buildings", "Historic houses", "Traditional Suffolk properties"],
      inclusions: ["Review of the existing roof", "Traditional slating or tiling", "Leadwork where required", "Material matching and conservation-led detailing"],
      benefits: ["An approach informed by Historic Conservation", "Care for the building’s established character", "Experience with sensitive and significant roofs"],
      projectExample: "Conservation work to a traditional roof where the covering, lead details and existing fabric must be considered together.",
    },
    {
      id: "slating-tiling-leadwork",
      name: "Slating, tiling & leadwork",
      shortDescription: "Skilled installation and repair of natural slate, traditional tiles and detailed leadwork.",
      fullDescription: "3A Roofing provides slating, tiling and leadwork as coordinated roofing disciplines. The service is suited to traditional and modern properties where sound weathering and carefully finished details are central to the result.",
      image: { src: asset("slate-roofing-craftsperson.webp"), alt: "3A Roofing craftsperson fixing natural slate on a pitched roof" },
      projectTypes: ["Natural slate roofs", "Traditional tiled roofs", "Roof repairs", "Detailed leadwork"],
      inclusions: ["Slate and tile installation", "Roof junction detailing", "Lead weathering details", "Repair and renewal work"],
      benefits: ["One team across connected roofing details", "Traditional craft skills", "Attention to the junctions that protect the roof"],
      projectExample: "A pitched roof package combining natural slate with carefully formed lead details at its junctions.",
    },
    {
      id: "domestic-reroofing",
      name: "Domestic reroofing",
      shortDescription: "Complete reroofing for private homes, including appropriate insulation and ventilation improvements.",
      fullDescription: "For Suffolk homeowners, 3A Roofing undertakes complete reroofing through the NFRC Competent Person Scheme. The work can incorporate insulation and ventilation improvements as part of a properly considered roof renewal.",
      image: { src: asset("suffolk-white-cottage-heritage-roof.webp"), alt: "White Suffolk house with a renewed traditional clay tile roof" },
      projectTypes: ["Complete roof replacement", "Traditional homes", "Pitched domestic roofs", "Insulation and ventilation upgrades"],
      inclusions: ["Existing roof review", "Renewal of roof coverings", "Associated roof detailing", "Insulation and ventilation improvements where appropriate"],
      benefits: ["A complete rather than piecemeal approach", "Work delivered through the NFRC scheme", "Details considered around the whole roof"],
      projectExample: "A complete renewal of a traditional tiled roof, coordinated with weathering details, insulation and ventilation needs.",
    },
    {
      id: "solar-heritage-buildings",
      name: "Solar for heritage buildings",
      shortDescription: "Considered solar PV installation for sensitive roofs, delivered with an electrical specialist partner.",
      fullDescription: "3A Roofing works with Marshall Electrical Ltd on solar PV for heritage buildings. 3A Roofing’s role focuses on integrating the installation sympathetically with slate, tile and lead roof coverings, while the electrical design and installation is undertaken by the specialist partner.",
      image: { src: asset("historic-estate-conservation.webp"), alt: "Historic estate building with complex slate roofs and tall decorative chimneys" },
      projectTypes: ["Heritage properties", "Slate roofs", "Tiled roofs", "Roofs with lead coverings"],
      inclusions: ["Roofing review", "Coordination with the electrical specialist", "Sensitive integration with the roof covering", "Weathering details around the installation"],
      benefits: ["Roofing and electrical responsibilities clearly coordinated", "Attention to sensitive roof coverings", "A considered approach to historic character"],
      projectExample: "A solar installation planned around the appearance and weathering details of a traditional roof.",
    },
    {
      id: "reclaimed-roofing-materials",
      name: "Reclaimed roofing materials",
      shortDescription: "Reclaimed tiles, slates, ridge tiles and bricks for compatible repairs and traditional roof work.",
      fullDescription: "The Copdock stockyard holds reclaimed tiles, slates, ridge tiles and bricks, alongside new Spanish slates. These materials help support compatible repairs and roofing work where colour, texture and local character matter.",
      image: { src: asset("suffolk-vernacular-clay-roof.webp"), alt: "Traditional Suffolk house with varied reclaimed clay roof tiles" },
      projectTypes: ["Material matching", "Traditional roof repairs", "Heritage roof coverings", "Local vernacular buildings"],
      inclusions: ["Reclaimed tiles and slates", "Reclaimed ridge tiles", "Reclaimed bricks", "New Spanish slates"],
      benefits: ["A practical source of characterful materials", "Better visual compatibility for traditional work", "Local stock held at Copdock"],
      projectExample: "Selecting reclaimed clay tiles to sit comfortably alongside an established Suffolk roof covering.",
    },
    {
      id: "professional-client-roofing",
      name: "Professional client roofing",
      shortDescription: "Organised roofing delivery for surveyors, architects, estates and managed properties.",
      fullDescription: "3A Roofing also works for professional industry clients on sensitive and substantial buildings. CHAS and Constructionline certification support a structured approach to safety, coordination and project delivery.",
      image: { src: asset("ipswich-corn-exchange-heritage-roof.webp"), alt: "Historic civic building with an extensive traditional tiled roof" },
      projectTypes: ["Managed estates", "Civic and historic buildings", "Architect-led work", "Professional client projects"],
      inclusions: ["Review of project information", "Site and access planning", "Coordination with the professional team", "Roofing delivery and close-out"],
      benefits: ["Experience working with professional teams", "CHAS and Constructionline certification", "Clear coordination around sensitive buildings"],
      projectExample: "A defined heritage roofing package delivered alongside a professional project team.",
    },
  ],
  projects: [
    { title: "Historic estate roof conservation", category: "Heritage roofing", description: "An extensive slate roof with multiple roof forms and ornate chimney stacks.", image: { src: asset("hero-heritage-estate-roof.webp"), alt: "Aerial view of an extensive historic estate with renewed slate roofs" }, featured: true },
    { title: "Traditional Suffolk house", category: "Clay tiling", description: "A renewed clay tile roof sitting naturally above a white-painted traditional property.", image: { src: asset("suffolk-white-cottage-heritage-roof.webp"), alt: "White Suffolk house with a traditional clay tile roof" } },
    { title: "Ecclesiastical roof work", category: "Historic building", description: "Traditional roofing to a flint building with distinctive arched windows and a complex roof form.", image: { src: asset("historic-flint-chapel-roof.webp"), alt: "Historic flint building beneath mature trees with a traditional tiled roof" } },
    { title: "Leadwork turret detailing", category: "Specialist leadwork", description: "Closely formed leadwork protecting the junctions around an ornate historic roof feature.", image: { src: asset("leadwork-turret-detail.webp"), alt: "Close view of detailed leadwork around a historic roof turret" } },
  ],
  reasons: [
    { title: "Conservation-led understanding", description: "Traditional roofs are approached with an understanding of their materials, architecture and established character." },
    { title: "Connected roofing disciplines", description: "Slating, tiling and leadwork are considered together so important roof junctions receive coordinated attention." },
    { title: "Qualified roofing team", description: "Roofing operatives are NVQ qualified or working towards qualification through apprenticeships." },
    { title: "Materials close at hand", description: "The Copdock stockyard supports matching work with reclaimed tiles, slates, ridges and bricks." },
  ],
  process: [
    { step: "01", title: "Initial conversation", description: "Share the building location, the work being considered and any photographs or project information already available." },
    { step: "02", title: "Roof and site review", description: "Where appropriate, the roof, access, materials and conservation considerations can be reviewed in context." },
    { step: "03", title: "Quotation and scope", description: "The proposed work is set out so the roofing scope and next decisions can be understood before scheduling." },
    { step: "04", title: "Planning and delivery", description: "Access, materials and sequencing are organised around the agreed roofing work and the needs of the property." },
  ],
  reviews: [
    { quote: "Your team managed to complete a significant amount of work despite the weather and the pandemic, which is a real credit to your skilled team.", customerName: "Susan McDonough MRICS", customerLocation: "The Landmark Trust", projectType: "Cavendish Hall" },
    { quote: "The restored roof fits in with the character of our old Suffolk manor house and is of a standard that will last for very many years.", customerName: "Sir Kenneth Carlisle", customerLocation: "Wyken Hall", projectType: "Historic manor house" },
    { quote: "Right from the start Simon and Anton and their team paid meticulous attention to detail. We cannot recommend 3A Roofing too highly.", customerName: "Michael", customerLocation: "Framlingham", projectType: "Listed timber-framed house" },
  ],
  serviceAreas: ["Copdock", "Ipswich", "Suffolk"],
  socialLinks: [],
  residentialCommercial: {
    residential: { title: "Homes and private properties", description: "Complete reroofing and traditional roof work for homeowners, including sensitive historic and listed properties.", points: ["Complete pitched-roof renewal", "Traditional slate and clay tile work", "Insulation and ventilation improvements"] },
    commercial: { title: "Professional and managed projects", description: "Heritage and roofing packages delivered for professional clients, estates and significant buildings.", points: ["Architect and surveyor-led work", "Listed and ecclesiastical buildings", "CHAS and Constructionline certified"] },
  },
  faqs: [
    { question: "What information is useful when first getting in touch?", answer: "The property location, a short description of the work and clear photographs are a useful starting point. Drawings or professional reports can also be included where available." },
    { question: "Can photographs be shared before a roof visit?", answer: "Yes. Wider views and close details can help explain the roof and visible concerns, although photographs may not replace a site review where the scope needs closer consideration." },
    { question: "Do you work on domestic and professionally managed projects?", answer: "Yes. 3A Roofing undertakes complete reroofing for private homes as well as heritage and roofing work for professional industry clients." },
    { question: "Where is 3A Roofing based?", answer: "3A Roofing is based at The Laurels in Copdock, near Ipswich, and works across Suffolk." },
  ],
  quoteFaqs: [
    { question: "Does this form send a real enquiry?", answer: "No. This concept form demonstrates the future enquiry experience. It validates in your browser but does not send or store any details." },
    { question: "What should the project description include?", answer: "Describe the building, the roofing work or concern, any access considerations and any dates or professional project information already known." },
    { question: "Are selected photographs uploaded?", answer: "No. The selected filename is shown locally for the demonstration, but the file does not leave your browser." },
  ],
  quote: {
    eyebrow: "Request a quotation",
    heading: "Tell us about the roof and the building beneath it.",
    introduction: "Share the essentials below and select photographs or plans if they help explain the property and proposed work. This is a demonstration of how a future enquiry could be prepared.",
    nextStep: "The usual next step would be an initial conversation, followed by a review of the roof or site where the scope needs closer consideration.",
    photoNote: "Clear photographs of the whole roof, visible details and access context are useful. Plans or professional reports can also help where available.",
    preferredTimeframes: ["As soon as practical", "Within 1–3 months", "Within 3–6 months", "More than 6 months", "Still planning"],
    preferredContactMethods: ["Telephone", "Email", "Either is fine"],
    propertyTypes: ["Private home", "Listed or heritage property", "Ecclesiastical building", "Professional or managed project", "Other"],
    consentLabel: "I understand this is a demonstration form and no enquiry will be sent.",
    demonstrationNote: "Demonstration only — this form does not contact 3A Roofing or any external service.",
  },
  callout: {
    eyebrow: "Planning roofing work?",
    heading: "Start with the building, the roof and what you already know.",
    description: "Share the property location, the work being considered and any photographs or project information available.",
    note: "Photographs, plans or reports can be selected on the quotation page.",
  },
  presentation: {
    servicesPreview: { eyebrow: "Specialist expertise", heading: "The right roofing approach for buildings with a story.", description: "Heritage conservation, traditional roofing craft and complete reroofing, explained clearly before the first enquiry." },
    projects: { eyebrow: "Selected work", heading: "Roofing that belongs to the building.", description: "Traditional coverings, conservation details and significant roofscapes from 3A Roofing’s approved project imagery." },
    reasons: { eyebrow: "Why 3A Roofing", heading: "Professional standards, grounded in craft.", description: "The conservation understanding, material knowledge and organisation needed for sensitive roofs and demanding projects." },
    process: { eyebrow: "A considered process", heading: "From the first conversation to a clearly planned roofing project." },
    reviews: { eyebrow: "Client testimony", heading: "Trusted with significant buildings and much-loved homes.", description: "Published feedback from clients who chose 3A Roofing for conservation and substantial roofing work." },
    serviceAreas: { eyebrow: "Local knowledge", heading: "Based near Ipswich, working across Suffolk.", description: "Practical experience of the traditional materials and architectural character found across the county." },
    servicesHero: { eyebrow: "Roofing services", heading: "Traditional skills, organised around the needs of the building.", description: "Explore 3A Roofing’s heritage, domestic and professional-client capabilities, from roof coverings and leadwork to complete reroofing and sensitive solar integration." },
    capability: { eyebrow: "Project capability", heading: "From Suffolk homes to professionally managed heritage buildings." },
    servicesProcess: { eyebrow: "From enquiry to scope", heading: "Useful information first. A closer roof review where it adds value.", description: "Share what you know, including photographs, drawings or reports. The next conversation can then focus on the building and the roofing details that matter." },
    relatedProjects: { eyebrow: "Relevant work", heading: "Different buildings. The same respect for material and detail." },
    footerNote: "Private website concept by T3 Labs — demonstration only",
    footerLegalItems: ["No live form submission", "No social profiles shown"],
  },
  visibility: { trustStrip: true, projects: true, reviews: true, serviceAreas: true, commercialResidentialSplit: true, whatsapp: false },
  seo: {
    homeTitle: "3A Roofing Ltd | Heritage Roofing in Ipswich & Suffolk",
    homeDescription: "Heritage roofing, traditional slating, tiling, leadwork and complete reroofing from 3A Roofing Ltd in Copdock, near Ipswich.",
    servicesTitle: "Heritage & Roofing Services | 3A Roofing Ltd",
    servicesDescription: "Explore 3A Roofing’s heritage, listed building, slating, tiling, leadwork, domestic reroofing and professional roofing services in Suffolk.",
    quoteTitle: "Request a Roofing Quotation | 3A Roofing Ltd",
    quoteDescription: "Prepare a demonstration roofing enquiry for 3A Roofing Ltd with project details, location and photographs.",
  },
} satisfies PremiumContractorConfig;
