import type { PremiumContractorConfig } from "@/types/premium-contractor";

const asset = (name: string) => `/assets/contractor-template-premium/${name}`;

export const premiumContractorSite = {
  basePath: "/contractor-template-premium",
  company: {
    name: "Alder & Stone Projects",
    shortName: "Alder & Stone",
    legalName: "Alder & Stone Projects Ltd",
    tagline: "Considered construction. Clearly managed.",
    description: "A fictional demonstration contractor for the T3 Labs premium website template.",
    logo: { src: asset("alder-stone-mark.svg"), alt: "Alder and Stone Projects" },
    logoLight: { src: asset("alder-stone-mark-light.svg"), alt: "Alder and Stone Projects" },
  },
  branding: {
    primaryColour: "#171a18",
    accentColour: "#b56f43",
    accentLightColour: "#d9976e",
    heroAccentColour: "#f0b28c",
    backgroundColour: "#f3f0e8",
    textColour: "#20231f",
    mutedColour: "#6d7069",
  },
  contact: {
    phone: "01632 960 482",
    phoneHref: "tel:+441632960482",
    email: "hello@alderandstone.example",
    address: "Northfield, United Kingdom",
    openingHours: "Monday to Friday, 8:00–17:30",
  },
  navigation: { showServices: true, showQuote: true, showProjects: true, showProcess: true },
  hero: {
    eyebrow: "Residential & commercial project delivery",
    heading: "A well-built project starts with a well-managed plan.",
    supportingText: "From extensions and refurbishment to specialist exterior work, we bring clear scope, careful coordination and considered workmanship to every stage.",
    image: { src: asset("architectural-extension-hero.webp"), alt: "Contemporary timber and glass extension to a British brick house" },
    primaryCta: "Request a quote",
    secondaryCta: "Explore our work",
    credibilityNote: "Serving Northfield and the surrounding region",
  },
  introduction: {
    eyebrow: "A more considered way to build",
    heading: "Practical construction expertise, organised around your property and your priorities.",
    paragraphs: [
      "Alder & Stone is a fictional multi-disciplinary contractor created to demonstrate this reusable premium website template. The content can be adapted for a builder, roofer, specialist membrane installer, landscaper or commercial contractor.",
      "The approach is simple: understand the scope, prepare a clear quotation and coordinate the work with respect for the property, programme and people involved.",
    ],
    image: { src: asset("timber-extension-detail.webp"), alt: "Precise timber cladding detail on a contemporary extension" },
  },
  trustItems: [
    { title: "Residential & commercial", supportingText: "Flexible delivery for homes, workplaces and managed sites." },
    { title: "Detailed quotations", supportingText: "A clear scope helps everyone understand what is included." },
    { title: "Planned communication", supportingText: "Practical updates from initial visit through to handover." },
    { title: "Considered coordination", supportingText: "Work sequenced around access, materials and other trades." },
  ],
  services: [
    {
      id: "extensions-structural-work",
      name: "Extensions & structural work",
      shortDescription: "New space shaped around the existing building, with the structure, envelope and finish coordinated as one project.",
      fullDescription: "We plan extension and structural projects around how the existing property works. From early site review through to the final junction details, the focus remains on a buildable scope, orderly sequencing and a finish that feels intentional.",
      image: { src: asset("architectural-extension-hero.webp"), alt: "Completed contemporary rear extension" },
      projectTypes: ["Rear and side extensions", "Structural openings", "Garden rooms", "Internal reconfiguration"],
      inclusions: ["Site review and scope development", "Coordination with drawings and specifications", "Groundworks, structure and envelope", "Internal finishing and handover"],
      benefits: ["One coordinated project plan", "Clear interfaces between trades", "Decisions recorded before key stages"],
      projectExample: "A light-filled rear extension coordinated around an occupied family home.",
    },
    {
      id: "refurbishment-interiors",
      name: "Refurbishment & interiors",
      shortDescription: "Measured upgrades to existing homes and workplaces, from complete refurbishments to carefully defined interior packages.",
      fullDescription: "Refurbishment work depends on understanding what is already there. We establish the condition, access and intended finish before organising the trades needed to move from strip-out to a clean, complete result.",
      image: { src: asset("oak-kitchen-refurbishment.webp"), alt: "Finished oak kitchen refurbishment with rooflight" },
      projectTypes: ["Whole-property refurbishment", "Kitchen and living spaces", "Commercial interiors", "Planned maintenance upgrades"],
      inclusions: ["Condition and access review", "Strip-out and preparation", "First and second fix coordination", "Finishes, snagging and handover"],
      benefits: ["A joined-up sequence", "Care around retained finishes", "Defined completion standards"],
      projectExample: "An open-plan refurbishment linking a period home to its garden.",
    },
    {
      id: "building-envelope",
      name: "Building envelope & exteriors",
      shortDescription: "Roofing, cladding and exterior packages planned to protect the building and present a crisp, durable finish.",
      fullDescription: "Exterior work succeeds at the junctions. We coordinate substrate preparation, weathering details, material interfaces and access so the completed envelope performs as a coherent system.",
      image: { src: asset("commercial-cladding-project.webp"), alt: "Completed charcoal metal-clad commercial building" },
      projectTypes: ["Roofing and waterproofing", "Metal and timber cladding", "External repairs", "Commercial envelope upgrades"],
      inclusions: ["Condition and interface review", "Access and protection planning", "Installation to agreed details", "Final inspection and close-out"],
      benefits: ["Attention to vulnerable junctions", "Coordinated exterior finishes", "Practical site planning"],
      projectExample: "A new commercial entrance and standing-seam clad façade package.",
    },
    {
      id: "specialist-projects",
      name: "Specialist project packages",
      shortDescription: "Defined packages for unusual materials, challenging access or projects that need focused technical coordination.",
      fullDescription: "Some projects do not fit a standard category. We help define the interfaces, information and sequence needed for specialist works, whether that involves membranes, detailed landscaping, groundworks or a bespoke external structure.",
      image: { src: asset("timber-extension-detail.webp"), alt: "Timber-clad building detail with black metal window frame" },
      projectTypes: ["Membrane and waterproofing packages", "Bespoke external structures", "Groundworks and hard landscaping", "Technical repair scopes"],
      inclusions: ["Scope and constraint review", "Material and detail coordination", "Trade sequencing", "Photographic close-out record"],
      benefits: ["Fewer grey areas", "Clear responsibilities", "A practical route through complex details"],
      projectExample: "A compact timber-clad studio formed around mature planting and restricted access.",
    },
  ],
  projects: [
    { title: "Northfield garden extension", location: "Northfield", category: "Residential extension", description: "A warm timber and glass addition designed to settle into an established garden.", image: { src: asset("architectural-extension-hero.webp"), alt: "Contemporary garden extension at dusk" }, featured: true },
    { title: "Oak courtyard kitchen", location: "Westborough", category: "Refurbishment", description: "An open-plan interior with natural oak joinery, rooflights and a clear connection to the garden.", image: { src: asset("oak-kitchen-refurbishment.webp"), alt: "Oak kitchen refurbishment with central island" } },
    { title: "Riverside workspace", location: "Riverside Estate", category: "Commercial envelope", description: "A restrained standing-seam façade and entrance package for a modern workspace.", image: { src: asset("commercial-cladding-project.webp"), alt: "Charcoal-clad commercial workspace exterior" } },
    { title: "Courtyard studio detail", location: "Ashwell", category: "Specialist build", description: "Precise timber cladding and metalwork formed around the original building and garden edge.", image: { src: asset("timber-extension-detail.webp"), alt: "Detailed timber-clad garden studio junction" } },
  ],
  reasons: [
    { title: "A scope you can understand", description: "We clarify what is included, which decisions are still needed and where another specialist may be involved." },
    { title: "Delivery with a clear rhythm", description: "Site activity, access and material lead times are planned so the work feels controlled rather than improvised." },
    { title: "Respect for the property", description: "Protection, housekeeping and considerate access are treated as part of the job, not an afterthought." },
    { title: "Workmanship at the junctions", description: "The meeting points between old and new, one trade and the next, receive the attention they deserve." },
  ],
  process: [
    { step: "01", title: "Initial conversation", description: "Tell us what you are considering, where the project is and what information is already available." },
    { step: "02", title: "Site visit & quotation", description: "We review the property, discuss priorities and prepare a quotation built around an agreed scope." },
    { step: "03", title: "Planning & delivery", description: "Key decisions, access and sequencing are organised before work begins, with updates as the project moves forward." },
    { step: "04", title: "Completion & handover", description: "We review the finished work, close out the agreed scope and leave a clear record of completion." },
  ],
  reviews: [
    { quote: "The quotation made the options easy to compare, and the team kept us informed when decisions were needed. The finished space feels like it has always belonged to the house.", customerName: "Demonstration review", customerLocation: "Northfield", projectType: "Residential extension" },
    { quote: "The site was organised, the sequence was clear and the handover was thorough. It was reassuring to know what was happening next throughout the project.", customerName: "Demonstration review", customerLocation: "Westborough", projectType: "Commercial refurbishment" },
  ],
  serviceAreas: ["Northfield", "Westborough", "Ashwell", "Riverside", "Meadow County", "Surrounding areas by arrangement"],
  socialLinks: [],
  residentialCommercial: {
    residential: { title: "Residential projects", description: "Considered work in occupied and vacant homes, planned around access, neighbours and the details that make a space feel resolved.", points: ["Extensions and reconfiguration", "Whole-property refurbishment", "Exterior upgrades and repairs"] },
    commercial: { title: "Commercial projects", description: "Defined packages for landlords, workplaces and managed sites where coordination, documentation and continuity matter.", points: ["Envelope and cladding packages", "Planned refurbishment", "Specialist maintenance scopes"] },
  },
  faqs: [
    { question: "What information is useful for an initial quotation?", answer: "A short description, the project address, any drawings or specifications, and a few clear photographs are a useful starting point. We can then advise what else is needed." },
    { question: "Can I send photographs before arranging a visit?", answer: "Yes. Photographs help explain the context and visible condition, although some projects will still need a site visit before the scope can be confirmed." },
    { question: "Do you undertake residential and commercial work?", answer: "This demonstration configuration is set up to show both. For a real contractor, either capability can be adjusted or hidden in the central configuration." },
    { question: "Which areas do you cover?", answer: "The fictional demonstration business is shown across Northfield and nearby areas. Replace this wording with the prospect’s verified service area before publication." },
  ],
  quoteFaqs: [
    { question: "Does this form send a real enquiry?", answer: "No. This is a demonstration form only. It validates in the browser and shows a sample confirmation without sending data anywhere." },
    { question: "What should I include in the project description?", answer: "Describe the property, the work you are considering, known problems, access constraints and any dates that affect the project." },
    { question: "Are uploaded photographs sent or stored?", answer: "No. In this demonstration, the filename is displayed locally in your browser and no file leaves the page." },
  ],
  quote: {
    eyebrow: "Request a quotation",
    heading: "Give us a clear starting point for your project.",
    introduction: "Share the essentials below and add photographs if they help explain the property or work. For a real contractor, this page can later be connected to an approved enquiry service.",
    nextStep: "The usual next step would be an initial conversation, followed by a site visit where the scope needs closer review.",
    photoNote: "Plans, sketches and clear photographs of the wider area and any problem details are particularly useful.",
    preferredTimeframes: ["As soon as practical", "Within 1–3 months", "Within 3–6 months", "More than 6 months", "Still planning"],
    preferredContactMethods: ["Telephone", "Email", "Either is fine"],
    propertyTypes: ["Residential", "Commercial", "Managed property / landlord", "Other"],
    consentLabel: "I understand this is a demonstration form and no enquiry will be sent.",
    demonstrationNote: "Demonstration only — this form does not contact a business or external service.",
  },
  callout: {
    eyebrow: "Planning a project?",
    heading: "Start with the scope. We’ll help make the next step clear.",
    description: "Tell us what you are considering, where the project is and what information you already have.",
    note: "Photographs, sketches or plans can be added on the quotation page.",
  },
  presentation: {
    servicesPreview: { eyebrow: "What we do", heading: "Defined services. One coordinated standard.", description: "The template adapts across construction sectors while keeping each service easy to understand and easy to enquire about." },
    projects: { eyebrow: "Selected work", heading: "Projects made clear through the details.", description: "A flexible gallery for genuine residential, commercial and specialist project photography." },
    reasons: { eyebrow: "Why the approach matters", heading: "Less uncertainty. Better decisions. A more controlled project.", description: "Good workmanship matters, but so does knowing what has been agreed and what happens next." },
    process: { eyebrow: "The project journey", heading: "A straightforward route from first conversation to handover." },
    reviews: { eyebrow: "Demonstration feedback", heading: "A review format that works with genuine words, not invented totals.", description: "Replace or hide this section when approved customer feedback is not available." },
    serviceAreas: { eyebrow: "Where we work", heading: "Local knowledge, with a sensible project radius.", description: "Service areas should always be replaced with verified locations for the real contractor." },
    servicesHero: { eyebrow: "Services", heading: "The right service, clearly scoped around the project.", description: "From larger residential work to commercial exteriors and specialist packages, each service can be configured around the contractor’s genuine capabilities." },
    capability: { eyebrow: "Project capability", heading: "A clear distinction between residential and commercial delivery." },
    servicesProcess: { eyebrow: "From enquiry to scope", heading: "Useful information first. A site visit where it adds value.", description: "Share what you know, including photographs and drawings. The next conversation can then focus on the details that matter rather than covering the basics again." },
    relatedProjects: { eyebrow: "Relevant work", heading: "Different sectors. The same attention to scope and finish." },
    footerNote: "Fictional demonstration template by T3 Labs",
    footerLegalItems: ["Privacy placeholder", "Cookie placeholder"],
  },
  visibility: { trustStrip: true, projects: true, reviews: true, serviceAreas: true, commercialResidentialSplit: true, whatsapp: false },
  seo: {
    homeTitle: "Premium Contractor Website Template | T3 Labs",
    homeDescription: "A reusable premium three-page contractor website template for established construction and specialist trade businesses.",
    servicesTitle: "Services | Alder & Stone Projects Demonstration",
    servicesDescription: "Explore the configurable residential, commercial and specialist services in the T3 Labs premium contractor template.",
    quoteTitle: "Request a Quote | Alder & Stone Projects Demonstration",
    quoteDescription: "A polished demonstration quotation form for the T3 Labs premium contractor website template.",
  },
} satisfies PremiumContractorConfig;
